"""refactor_automations

Revision ID: 90b64e8a3cdf
Revises: 9144aceaa48d
Create Date: 2026-07-17 17:09:43.229732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90b64e8a3cdf'
down_revision: Union[str, Sequence[str], None] = '9144aceaa48d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automations', sa.Column('description', sa.String(length=500), nullable=True))
    op.drop_column('automations', 'trigger_type')
    op.drop_column('automations', 'action_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automations', sa.Column('action_type', sa.VARCHAR(length=100), nullable=False))
    op.add_column('automations', sa.Column('trigger_type', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('automations', 'description')
    # ### end Alembic commands ###
